### ISSUE TITLE
Legend on line graphs

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#100]
Line graphs should display a legend, telling what each line denotes. Currently, you don't have much of an idea.

![Screenshot 2020-11-20 at 11 54 43](https://user-images.githubusercontent.com/55204/99792317-3520e800-2b27-11eb-8a30-296c589ca737.png)

**Comment by dybber** [comment]
And is there a problem with the first plot?

**Comment by JensKanstrupLarsen** [comment]
No, it looks as intended, that's just the way it looks.
It shows the "infection number" of each agent - when they are infected, it immediately jumps to 1000, and then it gradually decreases until it hits 0, upon which they become immune. It was the only interesting number the epidemic-model had to track, so that's why. A better usage would be in the `bread_n_butter.py` model to track the utility of each agent.

**Comment by JensKanstrupLarsen** [comment]
This PR only add legends to the second plot type; the first one (with each line being an agent) is more difficult, since each line is a series, and the legend adds one "descriptor" for each series.
